version: '3.8'

services:
  anti_jamming_service:
    build:
      context: .
      dockerfile: Dockerfile
    image: bulo-cloud-sentinel/anti-jamming-service:latest
    container_name: anti-jamming-service
    restart: unless-stopped
    privileged: true  # Required for USB device access
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
      - ./certs:/app/certs
    ports:
      - "8080:8080"
    environment:
      - ANTI_JAMMING_CONFIG=/app/config/config.yaml
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=${VAULT_TOKEN}
    devices:
      - /dev/bus/usb:/dev/bus/usb  # For USB devices (KrakenSDR, HackRF)
      - /dev/ttyUSB0:/dev/ttyUSB0  # For LoRa module
    networks:
      - bulo-network
    depends_on:
      - rabbitmq
      - vault

  rabbitmq:
    image: rabbitmq:3-management
    container_name: anti-jamming-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"  # AMQP port
      - "15672:15672"  # Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=bulo
      - RABBITMQ_DEFAULT_PASS=sentinel
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - bulo-network

  vault:
    image: vault:latest
    container_name: anti-jamming-vault
    restart: unless-stopped
    ports:
      - "8200:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=${VAULT_TOKEN}
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    volumes:
      - vault-data:/vault/data
    networks:
      - bulo-network

networks:
  bulo-network:
    external: true

volumes:
  rabbitmq-data:
  vault-data:
