apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-show-api
  namespace: bulocloud-sentinel
  labels:
    app: drone-show-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drone-show-api
  template:
    metadata:
      labels:
        app: drone-show-api
    spec:
      containers:
      - name: drone-show-api
        image: bulocloud-sentinel/drone-show-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: drone-show-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: drone-show-secrets
              key: redis-url
        - name: MINIO_URL
          value: "minio.bulocloud-sentinel.svc.cluster.local:9000"
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: drone-show-secrets
              key: minio-access-key
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: drone-show-secrets
              key: minio-secret-key
        - name: MINIO_BUCKET
          value: "drone-show"
        - name: SENTINEL_API_URL
          value: "http://bulocloud-sentinel-api.bulocloud-sentinel.svc.cluster.local:8000"
        - name: SENTINEL_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: drone-show-secrets
              key: sentinel-api-token
        - name: RTMP_SERVER
          value: "rtmp://rtmp-server.bulocloud-sentinel.svc.cluster.local:1935"
        - name: LOG_LEVEL
          value: "INFO"
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
