version: 2
updates:
  # Enable version updates for Python (root directory)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
    open-pull-requests-limit: 10
    target-branch: "main"
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "deps"
      include: "scope"
    # Specify reviewers for pull requests
    reviewers:
      - "BuloZB"
    # Specify assignees for pull requests
    assignees:
      - "BuloZB"
    # Group dependencies to reduce PR noise
    groups:
      # Group all AI/ML dependencies together
      ai-dependencies:
        patterns:
          - "openai"
          - "anthropic"
          - "google-generativeai"
          - "tiktoken"
          - "langchain*"
          - "transformers"
          - "sentence-transformers"
          - "accelerate"
          - "torch*"
          - "tensorflow*"
          - "onnx*"
      # Group all database dependencies together
      db-dependencies:
        patterns:
          - "sqlalchemy"
          - "alembic"
          - "peewee*"
          - "psycopg2*"
          - "pgvector"
          - "pymysql"
          - "pymongo"
          - "redis"
      # Group all security dependencies together
      security-dependencies:
        patterns:
          - "cryptography"
          - "pyopenssl"
          - "pyjwt"
          - "certifi"
          - "passlib"
          - "bcrypt"
          - "argon2-cffi"
      # Group all testing dependencies together
      testing-dependencies:
        patterns:
          - "pytest*"
          - "safety"
          - "bandit"
          - "semgrep"
          - "mypy"
          - "ruff"
    # Allow up-to-date dependencies to be maintained
    allow:
      # Allow updates for dependencies with security issues
      - dependency-type: "all"
    # Ignore certain dependencies
    ignore:
      # Ignore updates to packages that start with 'dev-'
      - dependency-name: "dev-*"
      # Ignore major updates to onnx due to compatibility issues
      - dependency-name: "onnx"
        versions: [">=2.0.0"]
      # Ignore major updates to torch due to compatibility issues
      - dependency-name: "torch"
        versions: [">=3.0.0"]
      # Ignore major version updates for all packages to reduce noise
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    # Apply security updates to vulnerable dependencies
    vulnerability-alerts: true

  # Python dependencies in backend
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "daily"
      time: "00:00"
    open-pull-requests-limit: 10
    target-branch: "main"
    labels:
      - "dependencies"
      - "security"
      - "backend"
    commit-message:
      prefix: "deps(backend)"
      include: "scope"
    reviewers:
      - "BuloZB"
    assignees:
      - "BuloZB"
    groups:
      security-updates:
        patterns:
          - "cryptography"
          - "pyopenssl"
          - "pyjwt"
          - "certifi"
          - "passlib"
          - "bcrypt"
          - "argon2-cffi"
    allow:
      - dependency-type: "all"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    vulnerability-alerts: true

  # Python dependencies in ai_analytics
  - package-ecosystem: "pip"
    directory: "/ai_analytics"
    schedule:
      interval: "daily"
      time: "00:00"
    open-pull-requests-limit: 10
    target-branch: "main"
    labels:
      - "dependencies"
      - "security"
      - "ai-analytics"
    commit-message:
      prefix: "deps(ai-analytics)"
      include: "scope"
    reviewers:
      - "BuloZB"
    assignees:
      - "BuloZB"
    groups:
      security-updates:
        patterns:
          - "cryptography"
          - "pyopenssl"
          - "pyjwt"
          - "certifi"
    allow:
      - dependency-type: "all"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    vulnerability-alerts: true

  # Python dependencies in security module
  - package-ecosystem: "pip"
    directory: "/security"
    schedule:
      interval: "daily"
      time: "00:00"
    open-pull-requests-limit: 10
    target-branch: "main"
    labels:
      - "dependencies"
      - "security"
      - "security-module"
    commit-message:
      prefix: "deps(security)"
      include: "scope"
    reviewers:
      - "BuloZB"
    assignees:
      - "BuloZB"
    groups:
      security-updates:
        patterns:
          - "*"
    allow:
      - dependency-type: "all"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    vulnerability-alerts: true

  # Enable version updates for JavaScript
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
      time: "00:00"
    open-pull-requests-limit: 10
    target-branch: "main"
    labels:
      - "dependencies"
      - "security"
      - "frontend"
    commit-message:
      prefix: "deps(npm)"
      include: "scope"
    reviewers:
      - "BuloZB"
    assignees:
      - "BuloZB"
    groups:
      security-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
    allow:
      - dependency-type: "all"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    vulnerability-alerts: true

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
    open-pull-requests-limit: 5
    target-branch: "main"
    labels:
      - "dependencies"
      - "security"
      - "docker"
    commit-message:
      prefix: "deps(docker)"
      include: "scope"
    reviewers:
      - "BuloZB"
    assignees:
      - "BuloZB"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    target-branch: "main"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "deps(actions)"
      include: "scope"
    reviewers:
      - "BuloZB"
    assignees:
      - "BuloZB"
