version: 2
updates:
  # Enable version updates for Python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    target-branch: "main"
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "deps"
      include: "scope"
    # Specify reviewers for pull requests
    reviewers:
      - "BuloZB"
    # Specify assignees for pull requests
    assignees:
      - "BuloZB"
    # Group dependencies to reduce PR noise
    groups:
      # Group all AI/ML dependencies together
      ai-dependencies:
        patterns:
          - "openai"
          - "anthropic"
          - "google-generativeai"
          - "tiktoken"
          - "langchain*"
          - "transformers"
          - "sentence-transformers"
          - "accelerate"
          - "torch*"
          - "tensorflow*"
          - "onnx*"
      # Group all database dependencies together
      db-dependencies:
        patterns:
          - "sqlalchemy"
          - "alembic"
          - "peewee*"
          - "psycopg2*"
          - "pgvector"
          - "pymysql"
          - "pymongo"
          - "redis"
      # Group all security dependencies together
      security-dependencies:
        patterns:
          - "cryptography"
          - "pyopenssl"
          - "pyjwt"
          - "certifi"
          - "passlib"
          - "bcrypt"
          - "argon2-cffi"
      # Group all testing dependencies together
      testing-dependencies:
        patterns:
          - "pytest*"
          - "safety"
          - "bandit"
          - "semgrep"
          - "mypy"
          - "ruff"
    # Allow up-to-date dependencies to be maintained
    allow:
      # Allow updates for dependencies with security issues
      - dependency-type: "all"
    # Ignore certain dependencies
    ignore:
      # Ignore updates to packages that start with 'dev-'
      - dependency-name: "dev-*"
      # Ignore major updates to onnx due to compatibility issues
      - dependency-name: "onnx"
        versions: [">=2.0.0"]
      # Ignore major updates to torch due to compatibility issues
      - dependency-name: "torch"
        versions: [">=3.0.0"]
    # Apply security updates to vulnerable dependencies
    vulnerability-alerts: true

  # Enable version updates for JavaScript
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    target-branch: "main"
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "npm"
      include: "scope"
    # Specify reviewers for pull requests
    reviewers:
      - "BuloZB"
    # Specify assignees for pull requests
    assignees:
      - "BuloZB"
    # Allow up-to-date dependencies to be maintained
    allow:
      # Allow updates for dependencies with security issues
      - dependency-type: "all"
    # Apply security updates to vulnerable dependencies
    vulnerability-alerts: true

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    target-branch: "main"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "github-actions"
      include: "scope"
    # Specify reviewers for pull requests
    reviewers:
      - "BuloZB"
    # Specify assignees for pull requests
    assignees:
      - "BuloZB"
