version: 2
updates:
  # Enable version updates for Python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    target-branch: "main"
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "pip"
      include: "scope"
    # Specify reviewers for pull requests
    reviewers:
      - "BuloZB"
    # Specify assignees for pull requests
    assignees:
      - "BuloZB"
    # Allow up-to-date dependencies to be maintained
    allow:
      # Allow updates for dependencies with security issues
      - dependency-type: "all"
        update-type: "security"
    # Ignore certain dependencies
    ignore:
      # Ignore updates to packages that start with 'dev-'
      # These are development dependencies that don't need to be updated
      - dependency-name: "dev-*"
    # Apply security updates to vulnerable dependencies
    vulnerability-alerts: true
    
  # Enable version updates for JavaScript
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    target-branch: "main"
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "npm"
      include: "scope"
    # Specify reviewers for pull requests
    reviewers:
      - "BuloZB"
    # Specify assignees for pull requests
    assignees:
      - "BuloZB"
    # Allow up-to-date dependencies to be maintained
    allow:
      # Allow updates for dependencies with security issues
      - dependency-type: "all"
        update-type: "security"
    # Apply security updates to vulnerable dependencies
    vulnerability-alerts: true
    
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    target-branch: "main"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "github-actions"
      include: "scope"
    # Specify reviewers for pull requests
    reviewers:
      - "BuloZB"
    # Specify assignees for pull requests
    assignees:
      - "BuloZB"
