name: OS Compatibility

on:
  push:
    branches: [ main ]
    paths:
      - 'drone_show_service/**'
  workflow_dispatch:

jobs:
  test-os-compatibility:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.11']
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        cd drone_show_service
        python -m pip install --upgrade pip
        pip install pytest pytest-asyncio
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      shell: bash
    
    - name: Test with pytest
      run: |
        cd drone_show_service
        pytest tests/test_utils.py
      shell: bash
