name: Push to Main Branch

on:
  push:
    branches: [ main ]
    paths:
      - 'drone_show_service/**'
  workflow_dispatch:

jobs:
  push-to-main:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
    
    - name: Push to Main Branch
      run: |
        git add drone_show_service/
        git commit -m "Update Drone Show microservice" || echo "No changes to commit"
        git push origin main
