apiVersion: v1
kind: ConfigMap
metadata:
  name: model-hub-config
  namespace: bulocloud-sentinel
data:
  config.yaml: |
    server:
      host: "0.0.0.0"
      port: 8070
      debug: false

    security:
      jwt_algorithm: "HS256"
      jwt_expiration: 3600  # Seconds

    mlflow:
      tracking_uri: "http://mlflow-service:5000"
      s3_endpoint_url: "http://minio-service:9000"

    logging:
      level: "INFO"
      file: "/app/logs/model_hub.log"
      max_size: 10  # MB
      backup_count: 5

---
apiVersion: v1
kind: Secret
metadata:
  name: model-hub-secrets
  namespace: bulocloud-sentinel
type: Opaque
data:
  postgres-password: cG9zdGdyZXM=  # "postgres" base64 encoded
  aws-access-key-id: bWluaW9hZG1pbg==  # "minioadmin" base64 encoded
  aws-secret-access-key: bWluaW9hZG1pbg==  # "minioadmin" base64 encoded
  jwt-secret: c3VwZXJzZWNyZXRrZXk=  # "supersecretkey" base64 encoded

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-hub
  namespace: bulocloud-sentinel
  labels:
    app: model-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-hub
  template:
    metadata:
      labels:
        app: model-hub
    spec:
      containers:
      - name: model-hub
        image: bulocloud-sentinel/model-hub:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8070
        env:
        - name: PORT
          value: "8070"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: model-hub-secrets
              key: postgres-password
        - name: POSTGRES_DB
          value: "model_hub"
        - name: POSTGRES_HOST
          value: "postgres-service"
        - name: POSTGRES_PORT
          value: "5432"
        - name: MLFLOW_TRACKING_URI
          value: "http://mlflow-service:5000"
        - name: MLFLOW_S3_ENDPOINT_URL
          value: "http://minio-service:9000"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: model-hub-secrets
              key: aws-access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: model-hub-secrets
              key: aws-secret-access-key
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: model-hub-secrets
              key: jwt-secret
        - name: LOG_LEVEL
          value: "INFO"
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /api/v1/health/liveness
            port: 8070
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/v1/health/readiness
            port: 8070
          initialDelaySeconds: 30
          periodSeconds: 10
        volumeMounts:
        - name: model-hub-config
          mountPath: /app/config
        - name: model-hub-logs
          mountPath: /app/logs
      volumes:
      - name: model-hub-config
        configMap:
          name: model-hub-config
      - name: model-hub-logs
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: model-hub-service
  namespace: bulocloud-sentinel
spec:
  selector:
    app: model-hub
  ports:
  - port: 8070
    targetPort: 8070
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: model-hub-ingress
  namespace: bulocloud-sentinel
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: model-hub.bulocloud-sentinel.local
    http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: model-hub-service
            port:
              number: 8070
