apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "drone-show.fullname" . }}
  labels:
    {{- include "drone-show.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "drone-show.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "drone-show.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "drone-show.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "drone-show.fullname" . }}-secrets
                  key: database-url
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "drone-show.fullname" . }}-secrets
                  key: redis-url
            - name: MINIO_URL
              value: {{ .Values.minio.url | quote }}
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "drone-show.fullname" . }}-secrets
                  key: minio-access-key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "drone-show.fullname" . }}-secrets
                  key: minio-secret-key
            - name: MINIO_BUCKET
              value: {{ .Values.minio.bucket | quote }}
            - name: SENTINEL_API_URL
              value: {{ .Values.sentinel.apiUrl | quote }}
            - name: SENTINEL_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "drone-show.fullname" . }}-secrets
                  key: sentinel-api-token
            - name: RTMP_SERVER
              value: {{ .Values.rtmp.server | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.logging.level | quote }}
            - name: MAX_DRONES
              value: {{ .Values.droneShow.maxDrones | quote }}
            - name: MIN_DRONE_SPACING
              value: {{ .Values.droneShow.minDroneSpacing | quote }}
            - name: DEFAULT_TAKEOFF_ALTITUDE
              value: {{ .Values.droneShow.defaultTakeoffAltitude | quote }}
            - name: DEFAULT_LANDING_ALTITUDE
              value: {{ .Values.droneShow.defaultLandingAltitude | quote }}
            - name: TIME_SYNC_INTERVAL
              value: {{ .Values.droneShow.timeSyncInterval | quote }}
            - name: TIME_SYNC_TOLERANCE
              value: {{ .Values.droneShow.timeSyncTolerance | quote }}
            - name: LED_UPDATE_RATE
              value: {{ .Values.droneShow.ledUpdateRate | quote }}
            - name: SIMULATION_UPDATE_RATE
              value: {{ .Values.droneShow.simulationUpdateRate | quote }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
