apiVersion: v1
kind: Secret
metadata:
  name: {{ include "drone-show.fullname" . }}-secrets
  labels:
    {{- include "drone-show.labels" . | nindent 4 }}
type: Opaque
data:
  database-url: {{ .Values.database.url | b64enc }}
  redis-url: {{ .Values.redis.url | b64enc }}
  minio-access-key: {{ .Values.minio.accessKey | b64enc }}
  minio-secret-key: {{ .Values.minio.secretKey | b64enc }}
  sentinel-api-token: {{ .Values.sentinel.apiToken | b64enc }}
