site_name: Drone Show Microservice
site_description: Documentation for the Drone Show microservice
site_author: Bulo.Cloud Sentinel Team
site_url: https://bulocloud-sentinel.example.com/docs/drone-show

repo_name: BuloZB/BuloCloudSentinel
repo_url: https://github.com/BuloZB/BuloCloudSentinel

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.critic
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: google
          rendering:
            show_source: true
            show_if_no_docstring: false
            show_root_heading: true
            show_root_toc_entry: true
            show_root_full_path: true
            show_object_full_path: false
            show_category_heading: true
            show_signature: true
            show_signature_annotations: true

nav:
  - Home: index.md
  - API Documentation: api.md
  - Blender Integration: blender_integration.md
  - Integration with Bulo.Cloud Sentinel: integration.md
  - Deployment: deployment.md
  - Code Reference:
    - Models: reference/models.md
    - Services: reference/services.md
    - API: reference/api.md
    - Utils: reference/utils.md
