server:
  address: 0.0.0.0:8080
  min_clients: 2
  max_clients: 100
  rounds: 50
  aggregation_method: fedavg
  timeout_seconds: 600
  mqtt_broker: mqtt_broker
  mqtt_port: 8883
  mqtt_topic: fl/model_updates
  tls_enabled: true
  ca_cert_path: /certs/ca.crt
  server_cert_path: /certs/server.crt
  server_key_path: /certs/server.key

model:
  embedding_dim: 512
  num_classes: 80  # COCO dataset classes
  model_head_type: mlp
  save_path: /models

model_hub:
  api_url: http://model-hub-service:8000/api/v1
  api_key: ""
