apiVersion: v1
kind: ConfigMap
metadata:
  name: sigint-service-config
  namespace: bulo-sentinel
data:
  postgres_host: "postgres"
  postgres_port: "5432"
  postgres_db: "sigint_service"
  rabbitmq_host: "rabbitmq"
  rabbitmq_port: "5672"
  rabbitmq_exchange: "bulo.sentinel.sigint"
  redis_host: "redis"
  redis_port: "6379"
  minio_endpoint: "minio:9000"
  minio_bucket_name: "sigint"
  minio_secure: "false"
  cors_origins: "http://localhost:3000,http://frontend:80"
  collector_polling_interval: "1.0"
  signal_analysis_confidence_threshold: "0.5"
  signal_analysis_max_duration: "60"
  direction_finding_min_collectors: "2"
  direction_finding_max_age: "60"
  threat_detection_confidence_threshold: "0.7"
  rate_limit_requests: "100"
  rate_limit_window_seconds: "60"
  max_recording_duration: "300"
  max_recording_size: "100"
