apiVersion: v1
kind: Secret
metadata:
  name: sigint-service-secrets
  namespace: bulo-sentinel
type: Opaque
data:
  # These are example values - in production, use proper secret management
  postgres_user: cG9zdGdyZXM=  # postgres
  postgres_password: cG9zdGdyZXM=  # postgres
  jwt_secret: c3VwZXJzZWNyZXRrZXk=  # supersecretkey
  rabbitmq_username: Z3Vlc3Q=  # guest
  rabbitmq_password: Z3Vlc3Q=  # guest
  redis_password: ""
  minio_access_key: bWluaW9hZG1pbg==  # minioadmin
  minio_secret_key: bWluaW9hZG1pbg==  # minioadmin
