apiVersion: v1
kind: Secret
metadata:
  name: sentinel-beacon-secrets
  namespace: bulo-sentinel
type: Opaque
data:
  # These are example values - in production, use proper secret management
  postgres_user: cGxhY2Vob2xkZXJ1c2VybmFtZQ==  # placeholderusername
  postgres_password: cGxhY2Vob2xkZXJwYXNzd29yZA==  # placeholderpassword
  jwt_secret: ""  # Generate with: openssl rand -hex 32 | base64
  rabbitmq_username: cGxhY2Vob2xkZXJ1c2VybmFtZQ==  # placeholderusername
  rabbitmq_password: cGxhY2Vob2xkZXJwYXNzd29yZA==  # placeholderpassword
  meshtastic_channel_psk: ""  # Optional encryption key
