apiVersion: v1
kind: Service
metadata:
  name: sentinel-beacon
  namespace: bulo-sentinel
  labels:
    app: sentinel-beacon
    component: tactical
spec:
  selector:
    app: sentinel-beacon
  ports:
  - port: 80
    targetPort: 8000
    name: http
  type: ClusterIP
