apiVersion: v1
kind: ConfigMap
metadata:
  name: tacs-config
  namespace: bulo-sentinel
data:
  postgres_host: "postgres"
  postgres_port: "5432"
  postgres_db: "tacs"
  rabbitmq_host: "rabbitmq"
  rabbitmq_port: "5672"
  rabbitmq_exchange: "bulo.sentinel.tacs"
  redis_host: "redis"
  redis_port: "6379"
  storage_type: "s3"
  s3_bucket: "tacs"
  s3_region: "us-east-1"
  s3_endpoint: "http://minio:9000"
  keycloak_url: "http://keycloak:8080"
  keycloak_realm: "bulo-sentinel"
  keycloak_client_id: "tacs"
  log_level: "INFO"
  cors_origins: "http://localhost:3000,http://frontend:80"
  target_association_threshold: "100.0"
  target_track_timeout: "300"
  fusion_default_method: "weighted_average"
  coordination_max_platforms: "10"
