apiVersion: v1
kind: Secret
metadata:
  name: tacs-secrets
  namespace: bulo-sentinel
type: Opaque
data:
  # These are example values - in production, use proper secret management
  postgres_user: cG9zdGdyZXM=  # postgres
  postgres_password: cG9zdGdyZXM=  # postgres
  secret_key: c3VwZXJzZWNyZXRrZXk=  # supersecretkey
  rabbitmq_user: Z3Vlc3Q=  # guest
  rabbitmq_password: Z3Vlc3Q=  # guest
  redis_password: ""
  s3_access_key: bWluaW8=  # minio
  s3_secret_key: bWluaW8xMjM=  # minio123
  keycloak_client_secret: ""
