{{- if .Values.persistentVolumeClaim.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ignition-sim-data
  labels:
    {{- include "ignition-sim.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistentVolumeClaim.accessModes | nindent 4 }}
  storageClassName: {{ .Values.persistentVolumeClaim.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.size }}
{{- end }}
