apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  {{- if and .Values.database.enabled .Values.api.enabled }}
  database-url: "postgresql+asyncpg://{{ .Values.database.credentials.user }}:{{ .Values.database.credentials.password }}@{{ .Values.database.name }}:{{ .Values.database.service.port }}/{{ .Values.database.credentials.database }}"
  postgres-user: {{ .Values.database.credentials.user | quote }}
  postgres-password: {{ .Values.database.credentials.password | quote }}
  {{- end }}
  
  {{- if and .Values.redis.enabled .Values.api.enabled }}
  redis-url: "redis://:{{ .Values.redis.credentials.password }}@{{ .Values.redis.name }}:{{ .Values.redis.service.port }}/0"
  redis-password: {{ .Values.redis.credentials.password | quote }}
  {{- end }}
  
  {{- if .Values.api.enabled }}
  secret-key: {{ .Values.secrets.secretKey | quote }}
  easa-api-key: {{ .Values.secrets.easaApiKey | quote }}
  faa-laanc-api-key: {{ .Values.secrets.faaLaancApiKey | quote }}
  {{- end }}
