{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.name }}
  labels:
    app: {{ .Values.api.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
  - port: {{ .Values.api.service.port }}
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: {{ .Values.api.name }}
    release: {{ .Release.Name }}
{{- end }}

{{- if .Values.database.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.name }}
  labels:
    app: {{ .Values.database.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.database.service.port }}
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app: {{ .Values.database.name }}
    release: {{ .Release.Name }}
{{- end }}

{{- if .Values.redis.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.name }}
  labels:
    app: {{ .Values.redis.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.redis.service.port }}
    targetPort: 6379
    protocol: TCP
    name: redis
  selector:
    app: {{ .Values.redis.name }}
    release: {{ .Release.Name }}
{{- end }}
