apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    component: tactical
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  postgres_host: {{ .Values.config.postgres.host | quote }}
  postgres_port: {{ .Values.config.postgres.port | quote }}
  postgres_db: {{ .Values.config.postgres.db | quote }}
  rabbitmq_host: {{ .Values.config.rabbitmq.host | quote }}
  rabbitmq_port: {{ .Values.config.rabbitmq.port | quote }}
  rabbitmq_exchange: {{ .Values.config.rabbitmq.exchange | quote }}
  redis_host: {{ .Values.config.redis.host | quote }}
  redis_port: {{ .Values.config.redis.port | quote }}
  minio_endpoint: {{ .Values.config.minio.endpoint | quote }}
  minio_bucket_name: {{ .Values.config.minio.bucketName | quote }}
  minio_secure: {{ .Values.config.minio.secure | quote }}
  cors_origins: {{ .Values.config.cors.origins | quote }}
  collector_polling_interval: {{ .Values.config.collector.pollingInterval | quote }}
  signal_analysis_confidence_threshold: {{ .Values.config.signalAnalysis.confidenceThreshold | quote }}
  signal_analysis_max_duration: {{ .Values.config.signalAnalysis.maxDuration | quote }}
  direction_finding_min_collectors: {{ .Values.config.directionFinding.minCollectors | quote }}
  direction_finding_max_age: {{ .Values.config.directionFinding.maxAge | quote }}
  threat_detection_confidence_threshold: {{ .Values.config.threatDetection.confidenceThreshold | quote }}
  rate_limit_requests: {{ .Values.config.rateLimit.requests | quote }}
  rate_limit_window_seconds: {{ .Values.config.rateLimit.windowSeconds | quote }}
  max_recording_duration: {{ .Values.config.recording.maxDuration | quote }}
  max_recording_size: {{ .Values.config.recording.maxSize | quote }}
