apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    component: tactical
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  postgres_user: {{ .Values.secrets.postgres.user | b64enc }}
  postgres_password: {{ .Values.secrets.postgres.password | b64enc }}
  jwt_secret: {{ .Values.secrets.jwt.secret | b64enc }}
  rabbitmq_username: {{ .Values.secrets.rabbitmq.username | b64enc }}
  rabbitmq_password: {{ .Values.secrets.rabbitmq.password | b64enc }}
  redis_password: {{ .Values.secrets.redis.password | b64enc }}
  minio_access_key: {{ .Values.secrets.minio.accessKey | b64enc }}
  minio_secret_key: {{ .Values.secrets.minio.secretKey | b64enc }}
