name: Bandit Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit
          
      - name: Run Bandit
        run: |
          bandit -r . -x ./tests,./venv -f json -o bandit-results.json
          
      - name: Upload Bandit scan results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: bandit-results.json
          category: bandit
        if: always()
        
      - name: Check for high severity issues
        run: |
          if grep -q '"issue_severity": "HIGH"' bandit-results.json; then
            echo "High severity security issues found!"
            exit 1
          fi
