name: Safety Dependency Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight


permissions:
  contents: read
  issues: read
  pull-requests: read
  actions: read
  security-events: read

jobs:
  safety:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install safety

      - name: Run Safety check
        run: |
          if [ -f requirements.txt ]; then
            safety check -r requirements.txt --output text > safety-report.txt || true
          else
            echo "No requirements.txt found" > safety-report.txt
          fi

          if [ -f requirements-secure.txt ]; then
            safety check -r requirements-secure.txt --output text >> safety-report.txt || true
          fi

          if [ -f requirements-updated.txt ]; then
            safety check -r requirements-updated.txt --output text >> safety-report.txt || true
          fi

      - name: Create Markdown report
        run: |
          echo "# Safety Scan Results" > safety-report.md
          echo "" >> safety-report.md
          echo "## Vulnerabilities Found" >> safety-report.md
          echo "" >> safety-report.md
          echo '```' >> safety-report.md
          cat safety-report.txt >> safety-report.md
          echo '```' >> safety-report.md

      - name: Upload Safety report
        uses: actions/upload-artifact@v4
        with:
          name: safety-report
          path: safety-report.md
