name: Simulation Tests

on:
  schedule:
    - cron: '0 0 * * *'  # Run every day at midnight
  push:
    branches: [ main ]
    paths:
      - 'sim/**'
      - '.github/workflows/sim.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'sim/**'
      - '.github/workflows/sim.yml'
  workflow_dispatch:


permissions:
  contents: read
  issues: read
  pull-requests: read
  actions: read
  security-events: read

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: osrf/ros:humble-desktop
      options: --user root
    steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y --no-install-recommends \
            python3-pip \
            python3-colcon-common-extensions \
            python3-vcstool \
            python3-pytest \
            python3-pytest-cov \
            git \
            wget \
            gnupg \
            lsb-release
          
          # Add Gazebo repository
          wget https://packages.osrfoundation.org/gazebo.gpg -O /usr/share/keyrings/pkgs-osrf-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/pkgs-osrf-archive-keyring.gpg] http://packages.osrfoundation.org/gazebo/ubuntu-stable $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/gazebo-stable.list > /dev/null
          
          # Install Ignition Gazebo and ROS 2 bridge
          apt-get update
          apt-get install -y --no-install-recommends \
            ignition-gazebo \
            ros-humble-ros-gz \
            ros-humble-ros-gz-bridge \
            ros-humble-ros-gz-sim
          
          # Install Python dependencies
          pip3 install -r sim/requirements.txt
      
      - name: Build ROS 2 workspace
        run: |
          mkdir -p /ros2_ws/src
          cp -r sim/ros2_ws/src/* /ros2_ws/src/
          cd /ros2_ws
          source /opt/ros/humble/setup.bash
          colcon build --symlink-install
      
      - name: Run unit tests
        run: |
          cd sim
          source /opt/ros/humble/setup.bash
          source /ros2_ws/install/setup.bash
          python -m pytest tests/unit --cov=sim --cov-report=xml
      
      - name: Start Ignition Gazebo
        run: |
          ignition gazebo -s -r sim/worlds/urban_small.sdf &
          sleep 5
      
      - name: Run integration tests
        run: |
          cd sim
          source /opt/ros/humble/setup.bash
          source /ros2_ws/install/setup.bash
          python -m pytest tests/integration --cov=sim --cov-report=xml --cov-append
      
      - name: Run swarm path test
        run: |
          cd sim
          source /opt/ros/humble/setup.bash
          source /ros2_ws/install/setup.bash
          python -m pytest tests/sitl/test_swarm_path.py -v
      
      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          file: sim/coverage.xml
          flags: simulation
          name: simulation-coverage
          fail_ci_if_error: false
