apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dock-driver.fullname" . }}-secrets
  labels:
    {{- include "dock-driver.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ .Values.secrets.jwt_secret | b64enc | quote }}
  dji-api-key: {{ .Values.secrets.dji_api_key | b64enc | quote }}
  dji-api-secret: {{ .Values.secrets.dji_api_secret | b64enc | quote }}
  dji-dock-sn: {{ .Values.secrets.dji_dock_sn | b64enc | quote }}
  heisha-username: {{ .Values.secrets.heisha_username | b64enc | quote }}
  heisha-password: {{ .Values.secrets.heisha_password | b64enc | quote }}
  mqtt-username: {{ .Values.secrets.mqtt_username | b64enc | quote }}
  mqtt-password: {{ .Values.secrets.mqtt_password | b64enc | quote }}
  power-management-jwt-token: {{ .Values.secrets.power_management_jwt_token | b64enc | quote }}
